name: Build PDFs (Listas)

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**.tex"
      - "src/**.bib"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file:
          - src/lista1.tex

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.file }}

      - name: Move PDF
        run: |
          mkdir -p pdf
          name=$(basename ${{ matrix.file }} .tex)
          mv $name.pdf pdf/$name.pdf
          echo "PDF_NAME=$name" >> $GITHUB_ENV

      - name: Commit PDF
        uses: EndBug/add-and-commit@v9
        with:
          add: "pdf/${{ env.PDF_NAME }}.pdf"
          message: "Atualiza PDF: ${{ env.PDF_NAME }}"
          default_author: github_actions